finalize-platform: finalize-module-sdks: do not build mainline SDKs
Stop building the mainline SDKs as part of finalize-module-sdks.
Instead, assume those have been build previously and add a new command
line option to point to the directory that holds the artifacts.

Bug: 481594013
Test: croot && ./build/tools/finalization/finalize-platform/main finalize-module-sdks --mainline-sdks-dir out/dist
Change-Id: I879535cd0eeedcdf77fddd4f975707784ec07b0a

diff --git a/tools/finalization/finalize-platform/main b/tools/finalization/finalize-platform/main
--- a/tools/finalization/finalize-platform/main
+++ b/tools/finalization/finalize-platform/main
@@ -35,6 +35,7 @@ fi
 shift
 
 patch_dir=""
+mainline_sdks_dir=""
 while [[ $# -gt 0 ]]; do
     case "$1" in
         --patch-dir)
@@ -45,11 +46,20 @@ while [[ $# -gt 0 ]]; do
             patch_dir="$(readlink -f "$2")"
             shift 2
             ;;
+        --mainline-sdks-dir)
+            if [[ -z "$2" ]]; then
+                error "--mainline-sdks-dir: missing <value>"
+                exit 1
+            fi
+            mainline_sdks_dir="$(readlink -f "$2")"
+            shift 2
+            ;;
     esac
 done
 
 case "$command" in
     finalize-module-sdks)
+        require_arg "--mainline-sdks-dir" "mainline_sdks_dir"
         source "$(dirname "$0")"/finalize-module-sdks.sh
         ;;
     finalize-resources)
